# Setting up BCP data
  
Notes:
* Get all available data from dropbox  
* Make id for kid vs mom (0 and 1)  
  
Workflow Outline:  
* Gather input text files 4 and 9, mom and child (separate files) 
* Clean data - remove excess columns, make the Participant IDs consistent(*may need original tag, talk to Krisitine*) 
* Add additional columns, "Sphingomyelin (mg)", "Phosphatidycholine (mg)", "healthy eating index", "child eating index", and a column for mom or child ID
* Concatenate files

In [9]:
import os, glob
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

## Get Data

In [10]:
# get data location
base_path = "/Users/nikkibytes/Documents/BCP_DATA"
text4_files=glob.glob(os.path.join(base_path, "set*/*/*/*04.txt"))
text9_files=glob.glob(os.path.join(base_path, "set*/*/*/*09.txt"))

In [11]:
txt4_mom_files = [x for x in text4_files if "Mom" in x]
txt4_child_files = [x for x in text4_files if "Child" in x]
print("Mom files: \n{} \n\nChild files: \n{}".format(txt4_mom_files, txt4_child_files))

Mom files:
['/Users/nikkibytes/Documents/BCP_DATA/set2/UNC/mom/UNCMomJuly04.txt', '/Users/nikkibytes/Documents/BCP_DATA/set2/UMN/mom/UMNMomJuly04.txt', '/Users/nikkibytes/Documents/BCP_DATA/set5/mom/mom/MomOct1804.txt', '/Users/nikkibytes/Documents/BCP_DATA/set4/mom/data/UMNUNCMom04.txt', '/Users/nikkibytes/Documents/BCP_DATA/set3/mom/data/BCPMomAP04.txt', '/Users/nikkibytes/Documents/BCP_DATA/set1/mom/data/BCPJulAugMom04.txt']

Child files:
['/Users/nikkibytes/Documents/BCP_DATA/set2/UNC/child/UNCChildJuly04.txt', '/Users/nikkibytes/Documents/BCP_DATA/set2/UMN/child/UMNChildJuly04.txt', '/Users/nikkibytes/Documents/BCP_DATA/set5/child/child/ChildOct1804.txt', '/Users/nikkibytes/Documents/BCP_DATA/set4/child/data/UMNUNCChild04.txt', '/Users/nikkibytes/Documents/BCP_DATA/set3/child/data/BCPChildAP04.txt']

In [12]:
txt9_mom_files = [x for x in text9_files if "Mom" in x]
txt9_child_files = [x for x in text9_files if "Child" in x]
print("Mom files: \n{} \n\nChild files: \n{}".format(txt9_mom_files, txt9_child_files))

Mom files:
['/Users/nikkibytes/Documents/BCP_DATA/set2/UNC/mom/UNCMomJuly09.txt', '/Users/nikkibytes/Documents/BCP_DATA/set2/UMN/mom/UMNMomJuly09.txt', '/Users/nikkibytes/Documents/BCP_DATA/set5/mom/mom/MomOct1809.txt', '/Users/nikkibytes/Documents/BCP_DATA/set4/mom/data/UMNUNCMom09.txt', '/Users/nikkibytes/Documents/BCP_DATA/set3/mom/data/BCPMomAP09.txt', '/Users/nikkibytes/Documents/BCP_DATA/set1/mom/data/BCPJulAugMom09.txt']

Child files:
['/Users/nikkibytes/Documents/BCP_DATA/set2/UNC/child/UNCChildJuly09.txt', '/Users/nikkibytes/Documents/BCP_DATA/set2/UMN/child/UMNChildJuly09.txt', '/Users/nikkibytes/Documents/BCP_DATA/set5/child/child/ChildOct1809.txt', '/Users/nikkibytes/Documents/BCP_DATA/set4/child/data/UMNUNCChild09.txt', '/Users/nikkibytes/Documents/BCP_DATA/set3/child/data/BCPChildAP09.txt']

## Cleaning up Data

In [13]:
txt4_mom_df_list = []
txt4_child_df_list = []

for file in txt4_mom_files:
    df = pd.read_csv(file,encoding='latin1', sep="\t")
    print("Filename: {} \nDataframe size: {}".format(file.split("/")[-1], df.shape))
    updated_df = df[["Participant ID", "Date of Intake", "Day of Intake", "Visit Number", "Site ID", "Total Grams", "Energy (kcal)", "Total Fat (g)", 
                  "Total Carbohydrate (g)", "Total Protein (g)", "Animal Protein (g)", "Vegetable Protein (g)", "Cholesterol (mg)", 
                  "Total Saturated Fatty Acids (SFA) (g)", "Total Monounsaturated Fatty Acids (MUFA) (g)", "Total Polyunsaturated Fatty Acids (PUFA) (g)", 
                  "Total Vitamin A Activity (International Units) (IU)", "Vitamin D (calciferol) (mcg)", "Galactose (g)", "Glucose (g)", "Lactose (g)", 
                  "Maltose (g)", "Sucrose (g)", "Total Dietary Fiber (g)", "Soluble Dietary Fiber (g)", "Insoluble Dietary Fiber (g)", "Total Folate (mcg)", 
                  "Vitamin B-12 (cobalamin) (mcg)", "Magnesium (mg)", "Iron (mg)", "Zinc (mg)", "Copper (mg)", "Selenium (mcg)", "PUFA 20:4 (arachidonic acid) (g)", 
                  "PUFA 20:5 (eicosapentaenoic acid [EPA]) (g)", "PUFA 22:6 (docosahexaenoic acid [DHA]) (g)", "Tryptophan (g)", "Threonine (g)", "Isoleucine (g)",
                  "Leucine (g)", "Lysine (g)", "Methionine (g)", "Cystine (g)", "Phenylalanine (g)", "Tyrosine (g)", "Valine (g)", "Arginine (g)", "Histidine (g)",
                  "Alanine (g)", "Aspartic Acid (g)", "Glutamic Acid (g)", "Glycine (g)", "Proline (g)", "Serine (g)", "Aspartame (mg)", "Saccharin (mg)", "Caffeine (mg)",
                  "Oxalic Acid (mg)", "Water (g)", "% Calories from Fat", "% Calories from Carbohydrate", "% Calories from Protein", "% Calories from Alcohol", 
                  "% Calories from SFA", "% Calories from MUFA", "% Calories from PUFA", "Polyunsaturated to Saturated Fat Ratio", "Cholesterol to Saturated Fatty Acid Index",
                  "Total Vitamin A Activity (Retinol Equivalents) (mcg)", "TRANS 18:1 (trans-octadecenoic acid) (g)", "TRANS 18:2 (trans-octadecadienoic acid) (g)", 
                  "TRANS 16:1 (trans-hexadecenoic acid) (g)", "Total Trans-Fatty Acids (TRANS) (g)", "Water (g)", "% Calories from Fat", "% Calories from Carbohydrate",
                  "% Calories from Protein", "% Calories from Alcohol", "% Calories from SFA", "% Calories from MUFA", "% Calories from PUFA", "Polyunsaturated to Saturated Fat Ratio",
                  "Cholesterol to Saturated Fatty Acid Index", "Total Vitamin A Activity (Retinol Equivalents) (mcg)", "TRANS 18:1 (trans-octadecenoic acid) (g)",
                  "TRANS 18:2 (trans-octadecadienoic acid) (g)", "TRANS 16:1 (trans-hexadecenoic acid) (g)", "Total Trans-Fatty Acids (TRANS) (g)", "Beta-Carotene (provitamin A carotenoid) (mcg)",
                  "Lutein + Zeaxanthin (mcg)", "Lycopene (mcg)", "Dietary Folate Equivalents (mcg)", "Natural Folate (food folate) (mcg)", "Synthetic Folate (folic acid) (mcg)",
                  "Niacin Equivalents (mg)", "Total Sugars (g)", "Omega-3 Fatty Acids (g)", "Manganese (mg)", "Vitamin E (International Units) (IU)", "Added Sugars (by Available Carbohydrate) (g)",
                  "Glycemic Index (glucose reference)", "Glycemic Load (glucose reference)", "Choline (mg)", "PUFA 18:3 n-3 (alpha-linolenic acid [ALA]) (g)"]]
    for val in updated_df["Participant ID"]:
        _id = str(val).split("_")[0]
        #print(_id)
        updated_df.replace(val, _id, inplace=True)
    #print(updated_df["Participant ID"])
    txt4_mom_df_list.append(updated_df)

    
for file in txt4_child_files:
    df = pd.read_csv(file,encoding='latin1', sep="\t")
    print("Filename: {} \nDataframe size: {}".format(file.split("/")[-1], df.shape))
    updated_df = df[["Participant ID", "Date of Intake", "Day of Intake", "Visit Number", "Site ID", "Total Grams", "Energy (kcal)", "Total Fat (g)", 
                  "Total Carbohydrate (g)", "Total Protein (g)", "Animal Protein (g)", "Vegetable Protein (g)", "Cholesterol (mg)", 
                  "Total Saturated Fatty Acids (SFA) (g)", "Total Monounsaturated Fatty Acids (MUFA) (g)", "Total Polyunsaturated Fatty Acids (PUFA) (g)", 
                  "Total Vitamin A Activity (International Units) (IU)", "Vitamin D (calciferol) (mcg)", "Galactose (g)", "Glucose (g)", "Lactose (g)", 
                  "Maltose (g)", "Sucrose (g)", "Total Dietary Fiber (g)", "Soluble Dietary Fiber (g)", "Insoluble Dietary Fiber (g)", "Total Folate (mcg)", 
                  "Vitamin B-12 (cobalamin) (mcg)", "Magnesium (mg)", "Iron (mg)", "Zinc (mg)", "Copper (mg)", "Selenium (mcg)", "PUFA 20:4 (arachidonic acid) (g)", 
                  "PUFA 20:5 (eicosapentaenoic acid [EPA]) (g)", "PUFA 22:6 (docosahexaenoic acid [DHA]) (g)", "Tryptophan (g)", "Threonine (g)", "Isoleucine (g)",
                  "Leucine (g)", "Lysine (g)", "Methionine (g)", "Cystine (g)", "Phenylalanine (g)", "Tyrosine (g)", "Valine (g)", "Arginine (g)", "Histidine (g)",
                  "Alanine (g)", "Aspartic Acid (g)", "Glutamic Acid (g)", "Glycine (g)", "Proline (g)", "Serine (g)", "Aspartame (mg)", "Saccharin (mg)", "Caffeine (mg)",
                  "Oxalic Acid (mg)", "Water (g)", "% Calories from Fat", "% Calories from Carbohydrate", "% Calories from Protein", "% Calories from Alcohol", 
                  "% Calories from SFA", "% Calories from MUFA", "% Calories from PUFA", "Polyunsaturated to Saturated Fat Ratio", "Cholesterol to Saturated Fatty Acid Index",
                  "Total Vitamin A Activity (Retinol Equivalents) (mcg)", "TRANS 18:1 (trans-octadecenoic acid) (g)", "TRANS 18:2 (trans-octadecadienoic acid) (g)", 
                  "TRANS 16:1 (trans-hexadecenoic acid) (g)", "Total Trans-Fatty Acids (TRANS) (g)", "Water (g)", "% Calories from Fat", "% Calories from Carbohydrate",
                  "% Calories from Protein", "% Calories from Alcohol", "% Calories from SFA", "% Calories from MUFA", "% Calories from PUFA", "Polyunsaturated to Saturated Fat Ratio",
                  "Cholesterol to Saturated Fatty Acid Index", "Total Vitamin A Activity (Retinol Equivalents) (mcg)", "TRANS 18:1 (trans-octadecenoic acid) (g)",
                  "TRANS 18:2 (trans-octadecadienoic acid) (g)", "TRANS 16:1 (trans-hexadecenoic acid) (g)", "Total Trans-Fatty Acids (TRANS) (g)", "Beta-Carotene (provitamin A carotenoid) (mcg)",
                  "Lutein + Zeaxanthin (mcg)", "Lycopene (mcg)", "Dietary Folate Equivalents (mcg)", "Natural Folate (food folate) (mcg)", "Synthetic Folate (folic acid) (mcg)",
                  "Niacin Equivalents (mg)", "Total Sugars (g)", "Omega-3 Fatty Acids (g)", "Manganese (mg)", "Vitamin E (International Units) (IU)", "Added Sugars (by Available Carbohydrate) (g)",
                  "Glycemic Index (glucose reference)", "Glycemic Load (glucose reference)", "Choline (mg)", "PUFA 18:3 n-3 (alpha-linolenic acid [ALA]) (g)"]]
    for val in updated_df["Participant ID"]:
        _id = str(val).split("_")[0]
        #print(_id)
        updated_df.replace(val, _id, inplace=True)
    #print(updated_df["Participant ID"])
    txt4_child_df_list.append(updated_df)

Filename: UNCMomJuly04.txt
Dataframe size: (26, 226)
Filename: UMNMomJuly04.txt
Dataframe size: (122, 226)
Filename: MomOct1804.txt
Dataframe size: (29, 226)
Filename: UMNUNCMom04.txt
Dataframe size: (17, 226)
Filename: BCPMomAP04.txt
Dataframe size: (27, 226)
Filename: BCPJulAugMom04.txt
Dataframe size: (35, 226)
Filename: UNCChildJuly04.txt
Dataframe size: (84, 226)
Filename: UMNChildJuly04.txt
Dataframe size: (206, 226)
Filename: ChildOct1804.txt
Dataframe size: (125, 226)
Filename: UMNUNCChild04.txt
Dataframe size: (113, 226)
Filename: BCPChildAP04.txt
Dataframe size: (57, 226)

## Modify mom dataframe

In [31]:
# add list of dataframes together
txt4_mom_concat_df = pd.concat(txt4_mom_df_list, ignore_index=True)
print(txt4_mom_concat_df.shape)
txt4_mom_concat_df.head()

(256, 104)

,Participant ID,Date of Intake,Day of Intake,Visit Number,Site ID,Total Grams,Energy (kcal),Total Fat (g),Total Carbohydrate (g),Total Protein (g),...,Niacin Equivalents (mg),Total Sugars (g),Omega-3 Fatty Acids (g),Manganese (mg),Vitamin E (International Units) (IU),Added Sugars (by Available Carbohydrate) (g),Glycemic Index (glucose reference),Glycemic Load (glucose reference),Choline (mg),PUFA 18:3 n-3 (alpha-linolenic acid [ALA]) (g)
0,011370,05/30/2017,2,2,UNC,2872.041,3098.347,155.139,342.807,100.001,...,51.546,134.092,4.121,4.157,18.835,59.016,58.504,181.208,293.112,4.086
1,011370,08/23/2017,3,1,UNC,2743.424,2800.854,105.956,358.233,115.060,...,52.776,185.565,3.582,3.603,14.619,97.642,54.701,183.927,499.411,3.486
2,017541,05/30/2017,2,1,UNC,2790.541,3118.359,156.893,341.159,101.941,...,53.032,126.078,4.358,4.038,21.658,50.419,58.746,181.272,290.828,4.324
3,043358,09/21/2017,4,1,UNC,1964.220,1937.645,77.584,233.575,82.651,...,40.912,112.576,0.938,2.525,14.065,84.990,58.354,125.826,629.616,0.775
4,107008,06/15/2017,4,1,UNC,5106.196,1982.607,97.905,229.872,74.010,...,41.231,117.427,1.224,5.262,31.164,25.129,50.219,97.498,310.720,1.211

In [32]:
# sort by participant ID
txt4_mom_concat_df = txt4_mom_concat_df.sort_values(by="Participant ID")
txt4_mom_concat_df.head()

,Participant ID,Date of Intake,Day of Intake,Visit Number,Site ID,Total Grams,Energy (kcal),Total Fat (g),Total Carbohydrate (g),Total Protein (g),...,Niacin Equivalents (mg),Total Sugars (g),Omega-3 Fatty Acids (g),Manganese (mg),Vitamin E (International Units) (IU),Added Sugars (by Available Carbohydrate) (g),Glycemic Index (glucose reference),Glycemic Load (glucose reference),Choline (mg),PUFA 18:3 n-3 (alpha-linolenic acid [ALA]) (g)
177,001999,09/18/2018,2,1,UMN,3557.076,2194.330,78.515,306.670,64.076,...,32.159,112.201,1.171,5.618,11.167,47.911,51.077,139.662,223.584,1.170
0,011370,05/30/2017,2,2,UNC,2872.041,3098.347,155.139,342.807,100.001,...,51.546,134.092,4.121,4.157,18.835,59.016,58.504,181.208,293.112,4.086
1,011370,08/23/2017,3,1,UNC,2743.424,2800.854,105.956,358.233,115.060,...,52.776,185.565,3.582,3.603,14.619,97.642,54.701,183.927,499.411,3.486
2,017541,05/30/2017,2,1,UNC,2790.541,3118.359,156.893,341.159,101.941,...,53.032,126.078,4.358,4.038,21.658,50.419,58.746,181.272,290.828,4.324
178,020784,09/25/2018,2,5,UMN,1524.126,1096.180,50.882,104.764,63.370,...,31.886,56.387,2.862,2.297,11.055,37.746,54.179,49.180,297.010,0.529

In [33]:
# add mom or child identifier column
txt4_mom_concat_df["Mom(0) or Child(1) ID"] = 0
print(txt4_mom_concat_df.shape)
txt4_mom_concat_df.head()

(256, 105)

,Participant ID,Date of Intake,Day of Intake,Visit Number,Site ID,Total Grams,Energy (kcal),Total Fat (g),Total Carbohydrate (g),Total Protein (g),...,Total Sugars (g),Omega-3 Fatty Acids (g),Manganese (mg),Vitamin E (International Units) (IU),Added Sugars (by Available Carbohydrate) (g),Glycemic Index (glucose reference),Glycemic Load (glucose reference),Choline (mg),PUFA 18:3 n-3 (alpha-linolenic acid [ALA]) (g),Mom(0) or Child(1) ID
177,001999,09/18/2018,2,1,UMN,3557.076,2194.330,78.515,306.670,64.076,...,112.201,1.171,5.618,11.167,47.911,51.077,139.662,223.584,1.170,0
0,011370,05/30/2017,2,2,UNC,2872.041,3098.347,155.139,342.807,100.001,...,134.092,4.121,4.157,18.835,59.016,58.504,181.208,293.112,4.086,0
1,011370,08/23/2017,3,1,UNC,2743.424,2800.854,105.956,358.233,115.060,...,185.565,3.582,3.603,14.619,97.642,54.701,183.927,499.411,3.486,0
2,017541,05/30/2017,2,1,UNC,2790.541,3118.359,156.893,341.159,101.941,...,126.078,4.358,4.038,21.658,50.419,58.746,181.272,290.828,4.324,0
178,020784,09/25/2018,2,5,UMN,1524.126,1096.180,50.882,104.764,63.370,...,56.387,2.862,2.297,11.055,37.746,54.179,49.180,297.010,0.529,0

#### Add "Sphingomyelin (mg)" column | calculation: choline / 4.366

In [35]:
txt4_mom_concat_df['Sphingomyelin (mg)'] = txt4_mom_concat_df[['Choline (mg)']].div(4.366)
txt4_mom_concat_df.head()

,Participant ID,Date of Intake,Day of Intake,Visit Number,Site ID,Total Grams,Energy (kcal),Total Fat (g),Total Carbohydrate (g),Total Protein (g),...,Omega-3 Fatty Acids (g),Manganese (mg),Vitamin E (International Units) (IU),Added Sugars (by Available Carbohydrate) (g),Glycemic Index (glucose reference),Glycemic Load (glucose reference),Choline (mg),PUFA 18:3 n-3 (alpha-linolenic acid [ALA]) (g),Mom(0) or Child(1) ID,Sphingomyelin (mg)
177,001999,09/18/2018,2,1,UMN,3557.076,2194.330,78.515,306.670,64.076,...,1.171,5.618,11.167,47.911,51.077,139.662,223.584,1.170,0,51.210261
0,011370,05/30/2017,2,2,UNC,2872.041,3098.347,155.139,342.807,100.001,...,4.121,4.157,18.835,59.016,58.504,181.208,293.112,4.086,0,67.135135
1,011370,08/23/2017,3,1,UNC,2743.424,2800.854,105.956,358.233,115.060,...,3.582,3.603,14.619,97.642,54.701,183.927,499.411,3.486,0,114.386395
2,017541,05/30/2017,2,1,UNC,2790.541,3118.359,156.893,341.159,101.941,...,4.358,4.038,21.658,50.419,58.746,181.272,290.828,4.324,0,66.612002
178,020784,09/25/2018,2,5,UMN,1524.126,1096.180,50.882,104.764,63.370,...,2.862,2.297,11.055,37.746,54.179,49.180,297.010,0.529,0,68.027943

#### Add "Phosphatidycholine (mg)" column | calculcation: choline * 0.479

In [37]:
txt4_mom_concat_df['Phosphatidycholine (mg)'] = txt4_mom_concat_df[['Choline (mg)']].multiply(0.479)
txt4_mom_concat_df.head()

,Participant ID,Date of Intake,Day of Intake,Visit Number,Site ID,Total Grams,Energy (kcal),Total Fat (g),Total Carbohydrate (g),Total Protein (g),...,Manganese (mg),Vitamin E (International Units) (IU),Added Sugars (by Available Carbohydrate) (g),Glycemic Index (glucose reference),Glycemic Load (glucose reference),Choline (mg),PUFA 18:3 n-3 (alpha-linolenic acid [ALA]) (g),Mom(0) or Child(1) ID,Sphingomyelin (mg),Phosphatidycholine (mg)
177,001999,09/18/2018,2,1,UMN,3557.076,2194.330,78.515,306.670,64.076,...,5.618,11.167,47.911,51.077,139.662,223.584,1.170,0,51.210261,107.096736
0,011370,05/30/2017,2,2,UNC,2872.041,3098.347,155.139,342.807,100.001,...,4.157,18.835,59.016,58.504,181.208,293.112,4.086,0,67.135135,140.400648
1,011370,08/23/2017,3,1,UNC,2743.424,2800.854,105.956,358.233,115.060,...,3.603,14.619,97.642,54.701,183.927,499.411,3.486,0,114.386395,239.217869
2,017541,05/30/2017,2,1,UNC,2790.541,3118.359,156.893,341.159,101.941,...,4.038,21.658,50.419,58.746,181.272,290.828,4.324,0,66.612002,139.306612
178,020784,09/25/2018,2,5,UMN,1524.126,1096.180,50.882,104.764,63.370,...,2.297,11.055,37.746,54.179,49.180,297.010,0.529,0,68.027943,142.267790

## Modify Child DataFrame

In [39]:
# add list of dataframes together
txt4_child_concat_df = pd.concat(txt4_child_df_list, ignore_index=True)
print(txt4_child_concat_df.shape)
txt4_child_concat_df.head()

(585, 104)

,Participant ID,Date of Intake,Day of Intake,Visit Number,Site ID,Total Grams,Energy (kcal),Total Fat (g),Total Carbohydrate (g),Total Protein (g),...,Niacin Equivalents (mg),Total Sugars (g),Omega-3 Fatty Acids (g),Manganese (mg),Vitamin E (International Units) (IU),Added Sugars (by Available Carbohydrate) (g),Glycemic Index (glucose reference),Glycemic Load (glucose reference),Choline (mg),PUFA 18:3 n-3 (alpha-linolenic acid [ALA]) (g)
0,2081,08/03/2017,4,1,UNC,545.135,357.150,20.400,38.037,6.783,...,5.028,25.474,0.357,0.060,3.646,24.812,77.079,28.980,84.258,0.322
1,2081,08/12/2017,6,2,UNC,815.400,532.440,28.188,57.420,12.215,...,8.491,27.770,0.549,0.080,10.649,47.815,91.338,51.826,127.368,0.458
2,17541,03/07/2017,2,1,UNC,608.189,747.515,27.169,93.414,33.578,...,14.689,36.197,0.760,1.318,8.517,9.153,51.845,44.336,279.438,0.610
3,17541,06/10/2017,6,2,UNC,921.555,1180.928,44.147,157.865,40.894,...,17.002,52.990,1.632,2.257,5.233,23.221,63.238,93.404,249.463,1.601
4,52977,07/22/2017,6,1,UNC,542.906,531.548,25.306,56.517,23.639,...,14.238,24.654,0.594,0.641,9.205,5.190,69.529,35.981,87.563,0.553

In [40]:
# sort by participant ID
txt4_child_concat_df = txt4_child_concat_df.sort_values(by="Participant ID")
txt4_child_concat_df.head()

,Participant ID,Date of Intake,Day of Intake,Visit Number,Site ID,Total Grams,Energy (kcal),Total Fat (g),Total Carbohydrate (g),Total Protein (g),...,Niacin Equivalents (mg),Total Sugars (g),Omega-3 Fatty Acids (g),Manganese (mg),Vitamin E (International Units) (IU),Added Sugars (by Available Carbohydrate) (g),Glycemic Index (glucose reference),Glycemic Load (glucose reference),Choline (mg),PUFA 18:3 n-3 (alpha-linolenic acid [ALA]) (g)
415,002081,10/25/2018,4,3,UNC,1151.059,757.031,40.078,81.641,17.367,...,12.073,39.484,0.781,0.114,15.141,67.984,91.338,73.688,181.094,0.652
416,011228,09/09/2018,0,6,UNC,488.625,538.858,20.148,77.691,11.818,...,9.290,30.766,0.363,0.624,2.689,35.887,62.384,46.977,25.735,0.355
417,011228,09/11/2018,2,7,UNC,654.903,495.016,14.124,73.995,20.871,...,12.611,46.355,0.136,0.608,1.048,15.860,56.837,39.844,105.258,0.136
291,011228,02/13/2018,2,4,UNC,741.438,494.959,13.295,81.800,14.336,...,11.909,33.495,0.298,0.913,1.137,26.482,63.831,48.127,59.032,0.296
290,011228,02/11/2018,0,3,UNC,1142.821,492.264,11.624,87.207,11.923,...,12.537,34.451,0.402,1.239,2.443,33.432,61.282,49.349,28.658,0.396

In [41]:
# add mom or child identifier column
txt4_child_concat_df["Mom(0) or Child(1) ID"] = 1
print(txt4_child_concat_df.shape)
txt4_child_concat_df.head()

(585, 105)

,Participant ID,Date of Intake,Day of Intake,Visit Number,Site ID,Total Grams,Energy (kcal),Total Fat (g),Total Carbohydrate (g),Total Protein (g),...,Total Sugars (g),Omega-3 Fatty Acids (g),Manganese (mg),Vitamin E (International Units) (IU),Added Sugars (by Available Carbohydrate) (g),Glycemic Index (glucose reference),Glycemic Load (glucose reference),Choline (mg),PUFA 18:3 n-3 (alpha-linolenic acid [ALA]) (g),Mom(0) or Child(1) ID
415,002081,10/25/2018,4,3,UNC,1151.059,757.031,40.078,81.641,17.367,...,39.484,0.781,0.114,15.141,67.984,91.338,73.688,181.094,0.652,1
416,011228,09/09/2018,0,6,UNC,488.625,538.858,20.148,77.691,11.818,...,30.766,0.363,0.624,2.689,35.887,62.384,46.977,25.735,0.355,1
417,011228,09/11/2018,2,7,UNC,654.903,495.016,14.124,73.995,20.871,...,46.355,0.136,0.608,1.048,15.860,56.837,39.844,105.258,0.136,1
291,011228,02/13/2018,2,4,UNC,741.438,494.959,13.295,81.800,14.336,...,33.495,0.298,0.913,1.137,26.482,63.831,48.127,59.032,0.296,1
290,011228,02/11/2018,0,3,UNC,1142.821,492.264,11.624,87.207,11.923,...,34.451,0.402,1.239,2.443,33.432,61.282,49.349,28.658,0.396,1

#### Add "Sphingomyelin (mg)" column | calculation: choline / 4.366

In [42]:
txt4_child_concat_df['Sphingomyelin (mg)'] = txt4_child_concat_df[['Choline (mg)']].div(4.366)
txt4_child_concat_df.head()

,Participant ID,Date of Intake,Day of Intake,Visit Number,Site ID,Total Grams,Energy (kcal),Total Fat (g),Total Carbohydrate (g),Total Protein (g),...,Omega-3 Fatty Acids (g),Manganese (mg),Vitamin E (International Units) (IU),Added Sugars (by Available Carbohydrate) (g),Glycemic Index (glucose reference),Glycemic Load (glucose reference),Choline (mg),PUFA 18:3 n-3 (alpha-linolenic acid [ALA]) (g),Mom(0) or Child(1) ID,Sphingomyelin (mg)
415,002081,10/25/2018,4,3,UNC,1151.059,757.031,40.078,81.641,17.367,...,0.781,0.114,15.141,67.984,91.338,73.688,181.094,0.652,1,41.478241
416,011228,09/09/2018,0,6,UNC,488.625,538.858,20.148,77.691,11.818,...,0.363,0.624,2.689,35.887,62.384,46.977,25.735,0.355,1,5.894411
417,011228,09/11/2018,2,7,UNC,654.903,495.016,14.124,73.995,20.871,...,0.136,0.608,1.048,15.860,56.837,39.844,105.258,0.136,1,24.108566
291,011228,02/13/2018,2,4,UNC,741.438,494.959,13.295,81.800,14.336,...,0.298,0.913,1.137,26.482,63.831,48.127,59.032,0.296,1,13.520843
290,011228,02/11/2018,0,3,UNC,1142.821,492.264,11.624,87.207,11.923,...,0.402,1.239,2.443,33.432,61.282,49.349,28.658,0.396,1,6.563903

#### Add "Phosphatidycholine (mg)" column | calculcation: choline * 0.479

In [44]:
txt4_child_concat_df['Phosphatidycholine (mg)'] = txt4_child_concat_df[['Choline (mg)']].multiply(0.479)
txt4_child_concat_df.head()

,Participant ID,Date of Intake,Day of Intake,Visit Number,Site ID,Total Grams,Energy (kcal),Total Fat (g),Total Carbohydrate (g),Total Protein (g),...,Manganese (mg),Vitamin E (International Units) (IU),Added Sugars (by Available Carbohydrate) (g),Glycemic Index (glucose reference),Glycemic Load (glucose reference),Choline (mg),PUFA 18:3 n-3 (alpha-linolenic acid [ALA]) (g),Mom(0) or Child(1) ID,Sphingomyelin (mg),Phosphatidycholine (mg)
415,002081,10/25/2018,4,3,UNC,1151.059,757.031,40.078,81.641,17.367,...,0.114,15.141,67.984,91.338,73.688,181.094,0.652,1,41.478241,86.744026
416,011228,09/09/2018,0,6,UNC,488.625,538.858,20.148,77.691,11.818,...,0.624,2.689,35.887,62.384,46.977,25.735,0.355,1,5.894411,12.327065
417,011228,09/11/2018,2,7,UNC,654.903,495.016,14.124,73.995,20.871,...,0.608,1.048,15.860,56.837,39.844,105.258,0.136,1,24.108566,50.418582
291,011228,02/13/2018,2,4,UNC,741.438,494.959,13.295,81.800,14.336,...,0.913,1.137,26.482,63.831,48.127,59.032,0.296,1,13.520843,28.276328
290,011228,02/11/2018,0,3,UNC,1142.821,492.264,11.624,87.207,11.923,...,1.239,2.443,33.432,61.282,49.349,28.658,0.396,1,6.563903,13.727182

### Add Mom and Child DataFrames together

In [46]:
final_df = pd.concat([txt4_mom_concat_df, txt4_child_concat_df])
final_df.tail()

,Participant ID,Date of Intake,Day of Intake,Visit Number,Site ID,Total Grams,Energy (kcal),Total Fat (g),Total Carbohydrate (g),Total Protein (g),...,Manganese (mg),Vitamin E (International Units) (IU),Added Sugars (by Available Carbohydrate) (g),Glycemic Index (glucose reference),Glycemic Load (glucose reference),Choline (mg),PUFA 18:3 n-3 (alpha-linolenic acid [ALA]) (g),Mom(0) or Child(1) ID,Sphingomyelin (mg),Phosphatidycholine (mg)
412,993015,04/14/2018,6,6,UMN,713.658,689.545,43.463,51.476,25.098,...,0.254,4.209,14.639,49.778,23.739,76.202,0.313,1,17.453504,36.500758
527,993015,07/22/2018,0,2,UMN,658.048,840.488,31.592,102.761,39.121,...,1.680,6.532,10.565,56.135,52.172,154.477,0.817,1,35.381814,73.994483
286,993015,07/19/2017,3,1,UMN,806.473,564.531,35.324,55.566,8.307,...,0.210,0.968,0.000,41.000,22.782,129.036,0.339,1,29.554741,61.808244
413,999647,04/13/2018,5,1,UNC,532.803,792.188,34.088,100.888,27.982,...,2.084,7.263,19.775,59.469,53.961,281.076,0.346,1,64.378378,134.635404
414,999647,04/18/2018,3,2,UNC,944.726,900.845,46.591,85.357,39.471,...,0.984,3.884,3.361,50.785,39.521,136.901,0.659,1,31.356161,65.575579

In [53]:
concat_filename = 'Draft1_mom_and_child'
csv_filename = "{}.csv".format(concat_filename)
tsv_filename = "{}.tsv".format(concat_filename)
xlsx_filename = "{}.xlsx".format(concat_filename)
concat_filepath = os.path.join(csv_filename)
xlsx_filepath = os.path.join(xlsx_filename)
tsv_filepath = os.path.join(tsv_filename)



#print( new_filepath)
# write concatentation to file
writer = pd.ExcelWriter(xlsx_filepath, engine='xlsxwriter')
final_df.to_excel(writer, sheet_name='Sheet1', index=False)
#concat_df.to_excel(concat_filepath)
final_df.to_csv(concat_filepath, index=False, sep="\t", header=True)
final_df.to_csv(tsv_filepath, index=False, sep="\t", header=True)
print("Written concat file, ", concat_filepath)
#umn_df = final_df[concat_df['Site ID'] == "UMN"]
#umn_df.head()

Written concat file,  Draft1_mom_and_child.csv

In [52]:
new_df = pd.read_csv("Draft1_mom_and_child.csv", sep="\t")
new_df.head()

,Participant ID,Date of Intake,Day of Intake,Visit Number,Site ID,Total Grams,Energy (kcal),Total Fat (g),Total Carbohydrate (g),Total Protein (g),...,Manganese (mg),Vitamin E (International Units) (IU),Added Sugars (by Available Carbohydrate) (g),Glycemic Index (glucose reference),Glycemic Load (glucose reference),Choline (mg),PUFA 18:3 n-3 (alpha-linolenic acid [ALA]) (g),Mom(0) or Child(1) ID,Sphingomyelin (mg),Phosphatidycholine (mg)
0,1999,09/18/2018,2,1,UMN,3557.076,2194.330,78.515,306.670,64.076,...,5.618,11.167,47.911,51.077,139.662,223.584,1.170,0,51.210261,107.096736
1,11370,05/30/2017,2,2,UNC,2872.041,3098.347,155.139,342.807,100.001,...,4.157,18.835,59.016,58.504,181.208,293.112,4.086,0,67.135135,140.400648
2,11370,08/23/2017,3,1,UNC,2743.424,2800.854,105.956,358.233,115.060,...,3.603,14.619,97.642,54.701,183.927,499.411,3.486,0,114.386395,239.217869
3,17541,05/30/2017,2,1,UNC,2790.541,3118.359,156.893,341.159,101.941,...,4.038,21.658,50.419,58.746,181.272,290.828,4.324,0,66.612002,139.306612
4,20784,09/25/2018,2,5,UMN,1524.126,1096.180,50.882,104.764,63.370,...,2.297,11.055,37.746,54.179,49.180,297.010,0.529,0,68.027943,142.267790