In [106]:
import os, glob
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

In [107]:
# get data location
base_path = "/Users/nikkibytes/Documents/BCP_DATA"
text4_files=glob.glob(os.path.join(base_path, "set*/*/*/*04.txt"))
text9_files=glob.glob(os.path.join(base_path, "set*/*/*/*09.txt"))

In [108]:
file_dict = {"set_04": {"mom":{}, "child": {}}, "set_09": {"mom": {}, "child": {}}}
file_dict['set_04']["mom"]["files"] = [x for x in text4_files if "Mom" in x]
file_dict['set_04']["child"]["files"] = [x for x in text4_files if "Child" in x]
#print("Text 4- \nMom files: \n{} \n\nChild files: \n{}\n".format(txt4_mom_files, txt4_child_files))
file_dict['set_09']["mom"]["files"] = [x for x in text9_files if "Mom" in x]
file_dict['set_09']["child"]["files"] = [x for x in text9_files if "Child" in x]
#print("Text 9- \nMom files: \n{} \n\nChild files: \n{}\n".format(txt9_mom_files, txt9_child_files))

In [109]:
temp_list = []            
for file in file_dict["set_04"]["mom"]["files"]:
    temp_df =  pd.read_csv(file, sep="\t", encoding='latin1')
    temp_list.append(temp_df)
    #print(temp_df.shape)
dfm4_original = pd.concat(temp_list, ignore_index=True)
print("Final dataframe size: ", dfm4.shape)
#dfm4_original.columns.values
dfm4_original.empty
#dfm4_original.head()

Final dataframe size:  (256, 226)

False

### Find Columns with NaN

In [110]:
empty_df = dfm4_original[dfm4_original.isna().any(axis=1)]
for a in dfm4_original: 
       if dfm4_original[a].isna().any(axis=0) == True:
            #print(dfm4_original[a].head(30))
            del dfm4_original[a]

In [111]:
dfm4_original.empty
np.where(pd.isnull(dfm4_original))
np.where(dfm4_original.applymap(lambda x: x == ''))

(array([], dtype=int64), array([], dtype=int64))

## Select Relevant Rows:

In [46]:
temp_list = []            
for file in file_dict["set_04"]["mom"]["files"]:
    temp_df = pd.read_csv(file,encoding='latin1', sep="\t")
    print("Loading file {}...........Dataframe size: {}".format(file.split("/")[-1], temp_df.shape))
    updated_df = temp_df[["Participant ID", "Date of Intake", "Day of Intake", "Visit Number", "Site ID", "Total Grams", "Energy (kcal)", "Total Fat (g)", 
                  "Total Carbohydrate (g)", "Total Protein (g)", "Animal Protein (g)", "Vegetable Protein (g)", "Cholesterol (mg)", 
                  "Total Saturated Fatty Acids (SFA) (g)", "Total Monounsaturated Fatty Acids (MUFA) (g)", "Total Polyunsaturated Fatty Acids (PUFA) (g)", 
                  "Total Vitamin A Activity (International Units) (IU)", "Vitamin D (calciferol) (mcg)", "Galactose (g)", "Glucose (g)", "Lactose (g)", 
                  "Maltose (g)", "Sucrose (g)", "Total Dietary Fiber (g)", "Soluble Dietary Fiber (g)", "Insoluble Dietary Fiber (g)", "Total Folate (mcg)", 
                  "Vitamin B-12 (cobalamin) (mcg)", "Magnesium (mg)", "Iron (mg)", "Zinc (mg)", "Copper (mg)", "Selenium (mcg)", "PUFA 20:4 (arachidonic acid) (g)", 
                  "PUFA 20:5 (eicosapentaenoic acid [EPA]) (g)", "PUFA 22:6 (docosahexaenoic acid [DHA]) (g)", "Tryptophan (g)", "Threonine (g)", "Isoleucine (g)",
                  "Leucine (g)", "Lysine (g)", "Methionine (g)", "Cystine (g)", "Phenylalanine (g)", "Tyrosine (g)", "Valine (g)", "Arginine (g)", "Histidine (g)",
                  "Alanine (g)", "Aspartic Acid (g)", "Glutamic Acid (g)", "Glycine (g)", "Proline (g)", "Serine (g)", "Aspartame (mg)", "Saccharin (mg)", "Caffeine (mg)",
                  "Oxalic Acid (mg)", "Water (g)", "% Calories from Fat", "% Calories from Carbohydrate", "% Calories from Protein", "% Calories from Alcohol", 
                  "% Calories from SFA", "% Calories from MUFA", "% Calories from PUFA", "Polyunsaturated to Saturated Fat Ratio", "Cholesterol to Saturated Fatty Acid Index",
                  "Total Vitamin A Activity (Retinol Equivalents) (mcg)", "TRANS 18:1 (trans-octadecenoic acid) (g)", "TRANS 18:2 (trans-octadecadienoic acid) (g)", 
                  "TRANS 16:1 (trans-hexadecenoic acid) (g)", "Total Trans-Fatty Acids (TRANS) (g)", "Water (g)", "% Calories from Fat", "% Calories from Carbohydrate",
                  "% Calories from Protein", "% Calories from Alcohol", "% Calories from SFA", "% Calories from MUFA", "% Calories from PUFA", "Polyunsaturated to Saturated Fat Ratio",
                  "Cholesterol to Saturated Fatty Acid Index", "Total Vitamin A Activity (Retinol Equivalents) (mcg)", "TRANS 18:1 (trans-octadecenoic acid) (g)",
                  "TRANS 18:2 (trans-octadecadienoic acid) (g)", "TRANS 16:1 (trans-hexadecenoic acid) (g)", "Total Trans-Fatty Acids (TRANS) (g)", "Beta-Carotene (provitamin A carotenoid) (mcg)",
                  "Lutein + Zeaxanthin (mcg)", "Lycopene (mcg)", "Dietary Folate Equivalents (mcg)", "Natural Folate (food folate) (mcg)", "Synthetic Folate (folic acid) (mcg)",
                  "Niacin Equivalents (mg)", "Total Sugars (g)", "Omega-3 Fatty Acids (g)", "Manganese (mg)", "Vitamin E (International Units) (IU)", "Added Sugars (by Available Carbohydrate) (g)",
                  "Glycemic Index (glucose reference)", "Glycemic Load (glucose reference)", "Choline (mg)", "PUFA 18:3 n-3 (alpha-linolenic acid [ALA]) (g)"]]
    # Update ID to be consistent -- keeping only first 6 digits, no extra "_" tags
    for val in updated_df["Participant ID"]:
        _id = str(val).split("_")[0]
        #print(_id)
        updated_df.replace(val, _id, inplace=True)
    #print(updated_df["Participant ID"])
    temp_list.append(updated_df)
    #print(file)
    #temp_df =  pd.read_csv(file, sep="\t", encoding='latin1')
    #temp_list.append(temp_df)
    #print(temp_df.shape)
dfm4 = pd.concat(temp_list, ignore_index=True)
print("Final dataframe size: ", dfm4.shape)
dfm4.head()

Loading file UNCMomJuly04.txt...........Dataframe size: (26, 226)
Loading file UMNMomJuly04.txt...........Dataframe size: (122, 226)
Loading file MomOct1804.txt...........Dataframe size: (29, 226)
Loading file UMNUNCMom04.txt...........Dataframe size: (17, 226)
Loading file BCPMomAP04.txt...........Dataframe size: (27, 226)
Loading file BCPJulAugMom04.txt...........Dataframe size: (35, 226)
Final dataframe size:  (256, 104)

,Participant ID,Date of Intake,Day of Intake,Visit Number,Site ID,Total Grams,Energy (kcal),Total Fat (g),Total Carbohydrate (g),Total Protein (g),...,Niacin Equivalents (mg),Total Sugars (g),Omega-3 Fatty Acids (g),Manganese (mg),Vitamin E (International Units) (IU),Added Sugars (by Available Carbohydrate) (g),Glycemic Index (glucose reference),Glycemic Load (glucose reference),Choline (mg),PUFA 18:3 n-3 (alpha-linolenic acid [ALA]) (g)
0,011370,05/30/2017,2,2,UNC,2872.041,3098.347,155.139,342.807,100.001,...,51.546,134.092,4.121,4.157,18.835,59.016,58.504,181.208,293.112,4.086
1,011370,08/23/2017,3,1,UNC,2743.424,2800.854,105.956,358.233,115.060,...,52.776,185.565,3.582,3.603,14.619,97.642,54.701,183.927,499.411,3.486
2,017541,05/30/2017,2,1,UNC,2790.541,3118.359,156.893,341.159,101.941,...,53.032,126.078,4.358,4.038,21.658,50.419,58.746,181.272,290.828,4.324
3,043358,09/21/2017,4,1,UNC,1964.220,1937.645,77.584,233.575,82.651,...,40.912,112.576,0.938,2.525,14.065,84.990,58.354,125.826,629.616,0.775
4,107008,06/15/2017,4,1,UNC,5106.196,1982.607,97.905,229.872,74.010,...,41.231,117.427,1.224,5.262,31.164,25.129,50.219,97.498,310.720,1.211

In [47]:
dfm4 = dfm4.sort_values(by="Participant ID")
dfm4.head()

,Participant ID,Date of Intake,Day of Intake,Visit Number,Site ID,Total Grams,Energy (kcal),Total Fat (g),Total Carbohydrate (g),Total Protein (g),...,Niacin Equivalents (mg),Total Sugars (g),Omega-3 Fatty Acids (g),Manganese (mg),Vitamin E (International Units) (IU),Added Sugars (by Available Carbohydrate) (g),Glycemic Index (glucose reference),Glycemic Load (glucose reference),Choline (mg),PUFA 18:3 n-3 (alpha-linolenic acid [ALA]) (g)
177,001999,09/18/2018,2,1,UMN,3557.076,2194.330,78.515,306.670,64.076,...,32.159,112.201,1.171,5.618,11.167,47.911,51.077,139.662,223.584,1.170
0,011370,05/30/2017,2,2,UNC,2872.041,3098.347,155.139,342.807,100.001,...,51.546,134.092,4.121,4.157,18.835,59.016,58.504,181.208,293.112,4.086
1,011370,08/23/2017,3,1,UNC,2743.424,2800.854,105.956,358.233,115.060,...,52.776,185.565,3.582,3.603,14.619,97.642,54.701,183.927,499.411,3.486
2,017541,05/30/2017,2,1,UNC,2790.541,3118.359,156.893,341.159,101.941,...,53.032,126.078,4.358,4.038,21.658,50.419,58.746,181.272,290.828,4.324
178,020784,09/25/2018,2,5,UMN,1524.126,1096.180,50.882,104.764,63.370,...,31.886,56.387,2.862,2.297,11.055,37.746,54.179,49.180,297.010,0.529

In [48]:
# add mom or child identifier column
dfm4["Mom(0) or Child(1) ID"] = 0
print(dfm4.shape)
dfm4["Mom(0) or Child(1) ID"].head()

(256, 105)

177    0
0      0
1      0
2      0
178    0
Name: Mom(0) or Child(1) ID, dtype: int64

In [49]:
dfm4['Sphingomyelin (mg)'] = dfm4[['Choline (mg)']].div(4.366)
dfm4['Sphingomyelin (mg)'].head()

177     51.210261
0       67.135135
1      114.386395
2       66.612002
178     68.027943
Name: Sphingomyelin (mg), dtype: float64

In [50]:
dfm4['Phosphatidycholine (mg)'] = dfm4[['Choline (mg)']].multiply(0.479)
dfm4['Phosphatidycholine (mg)'].head()

177    107.096736
0      140.400648
1      239.217869
2      139.306612
178    142.267790
Name: Phosphatidycholine (mg), dtype: float64

In [51]:
avg_df=dfm4.groupby(["Participant ID", "Visit Number"]).mean(numeric_only=True)
#reset index
avg_df.reset_index(inplace=True)  
avg_df.head()

,Participant ID,Visit Number,Day of Intake,Total Grams,Energy (kcal),Total Fat (g),Total Carbohydrate (g),Total Protein (g),Animal Protein (g),Vegetable Protein (g),...,Manganese (mg),Vitamin E (International Units) (IU),Added Sugars (by Available Carbohydrate) (g),Glycemic Index (glucose reference),Glycemic Load (glucose reference),Choline (mg),PUFA 18:3 n-3 (alpha-linolenic acid [ALA]) (g),Mom(0) or Child(1) ID,Sphingomyelin (mg),Phosphatidycholine (mg)
0,001999,1,2.0,3557.076,2194.330,78.515,306.670,64.076,23.277,40.800,...,5.618,11.167,47.911,51.077,139.662,223.584,1.170,0.0,51.210261,107.096736
1,011370,1,3.0,2743.424,2800.854,105.956,358.233,115.060,88.510,26.550,...,3.603,14.619,97.642,54.701,183.927,499.411,3.486,0.0,114.386395,239.217869
2,011370,2,2.0,2872.041,3098.347,155.139,342.807,100.001,47.819,52.182,...,4.157,18.835,59.016,58.504,181.208,293.112,4.086,0.0,67.135135,140.400648
3,017541,1,2.0,2790.541,3118.359,156.893,341.159,101.941,48.123,53.818,...,4.038,21.658,50.419,58.746,181.272,290.828,4.324,0.0,66.612002,139.306612
4,020784,5,2.0,1524.126,1096.180,50.882,104.764,63.370,47.624,15.748,...,2.297,11.055,37.746,54.179,49.180,297.010,0.529,0.0,68.027943,142.267790

In [70]:
concat_filename = "Mom_BCP_dataset4"
csv_filename = "{}.csv".format(concat_filename)
tsv_filename = "{}.tsv".format(concat_filename)
xlsx_filename = "{}.xlsx".format(concat_filename)
concat_filepath = os.path.join(csv_filename)
xlsx_filepath = os.path.join(xlsx_filename)
tsv_filepath = os.path.join(tsv_filename)

#print( new_filepath)
# write concatentation to file
writer = pd.ExcelWriter(xlsx_filepath, engine='xlsxwriter')
avg_df.to_excel(writer, sheet_name='Sheet1', index=False)
#concat_df.to_excel(concat_filepath)
avg_df.to_csv(concat_filepath, index=False, sep="\t", header=True)
avg_df.to_csv(tsv_filepath, index=False, sep="\t", header=True)
print("Written concat file, ", concat_filepath)
#umn_df = final_df[concat_df['Site ID'] == "UMN"]
#umn_df.head()

Written concat file,  Mom_BCP_dataset4.csv

In [55]:
avg_df["Participant ID"].unique()
avg_df["Day of Intake"].unique()
avg_df.columns.values

array(['Participant ID', 'Visit Number', 'Day of Intake', 'Total Grams',
       'Energy (kcal)', 'Total Fat (g)', 'Total Carbohydrate (g)',
       'Total Protein (g)', 'Animal Protein (g)', 'Vegetable Protein (g)',
       'Cholesterol (mg)', 'Total Saturated Fatty Acids (SFA) (g)',
       'Total Monounsaturated Fatty Acids (MUFA) (g)',
       'Total Polyunsaturated Fatty Acids (PUFA) (g)',
       'Total Vitamin A Activity (International Units) (IU)',
       'Vitamin D (calciferol) (mcg)', 'Galactose (g)', 'Glucose (g)',
       'Lactose (g)', 'Maltose (g)', 'Sucrose (g)',
       'Total Dietary Fiber (g)', 'Soluble Dietary Fiber (g)',
       'Insoluble Dietary Fiber (g)', 'Total Folate (mcg)',
       'Vitamin B-12 (cobalamin) (mcg)', 'Magnesium (mg)', 'Iron (mg)',
       'Zinc (mg)', 'Copper (mg)', 'Selenium (mcg)',
       'PUFA 20:4 (arachidonic acid) (g)',
       'PUFA 20:5 (eicosapentaenoic acid [EPA]) (g)',
       'PUFA 22:6 (docosahexaenoic acid [DHA]) (g)', 'Tryptophan (g)',
       'Threonine (g)', 'Isoleucine (g)', 'Leucine (g)', 'Lysine (g)',
       'Methionine (g)', 'Cystine (g)', 'Phenylalanine (g)',
       'Tyrosine (g)', 'Valine (g)', 'Arginine (g)', 'Histidine (g)',
       'Alanine (g)', 'Aspartic Acid (g)', 'Glutamic Acid (g)',
       'Glycine (g)', 'Proline (g)', 'Serine (g)', 'Aspartame (mg)',
       'Saccharin (mg)', 'Caffeine (mg)', 'Oxalic Acid (mg)', 'Water (g)',
       '% Calories from Fat', '% Calories from Carbohydrate',
       '% Calories from Protein', '% Calories from Alcohol',
       '% Calories from SFA', '% Calories from MUFA',
       '% Calories from PUFA', 'Polyunsaturated to Saturated Fat Ratio',
       'Cholesterol to Saturated Fatty Acid Index',
       'Total Vitamin A Activity (Retinol Equivalents) (mcg)',
       'TRANS 18:1 (trans-octadecenoic acid) (g)',
       'TRANS 18:2 (trans-octadecadienoic acid) (g)',
       'TRANS 16:1 (trans-hexadecenoic acid) (g)',
       'Total Trans-Fatty Acids (TRANS) (g)', 'Water (g)',
       '% Calories from Fat', '% Calories from Carbohydrate',
       '% Calories from Protein', '% Calories from Alcohol',
       '% Calories from SFA', '% Calories from MUFA',
       '% Calories from PUFA', 'Polyunsaturated to Saturated Fat Ratio',
       'Cholesterol to Saturated Fatty Acid Index',
       'Total Vitamin A Activity (Retinol Equivalents) (mcg)',
       'TRANS 18:1 (trans-octadecenoic acid) (g)',
       'TRANS 18:2 (trans-octadecadienoic acid) (g)',
       'TRANS 16:1 (trans-hexadecenoic acid) (g)',
       'Total Trans-Fatty Acids (TRANS) (g)',
       'Beta-Carotene (provitamin A carotenoid) (mcg)',
       'Lutein + Zeaxanthin (mcg)', 'Lycopene (mcg)',
       'Dietary Folate Equivalents (mcg)',
       'Natural Folate (food folate) (mcg)',
       'Synthetic Folate (folic acid) (mcg)', 'Niacin Equivalents (mg)',
       'Total Sugars (g)', 'Omega-3 Fatty Acids (g)', 'Manganese (mg)',
       'Vitamin E (International Units) (IU)',
       'Added Sugars (by Available Carbohydrate) (g)',
       'Glycemic Index (glucose reference)',
       'Glycemic Load (glucose reference)', 'Choline (mg)',
       'PUFA 18:3 n-3 (alpha-linolenic acid [ALA]) (g)',
       'Mom(0) or Child(1) ID', 'Sphingomyelin (mg)',
       'Phosphatidycholine (mg)'], dtype=object)